# Generated by Django 2.2.6 on 2021-03-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210319_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Введите текст Вашей публикации', verbose_name='Текст публикации'),
        ),
    ]
